# Generated by Django 4.2.5 on 2023-10-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_board_00', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardTestTable',
            new_name='board_test_table',
        ),
    ]
